version: "3"
services:
  database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5433:5432
  # backend:
  #   build: .
  #   ports:
  #     - 8000:8000
    
volumes:
  database-data:
